### ISSUE TITLE
[Bug]: 2023.1 incompatible 

### ISSUE THREAD

**Issue by RegressiaUK** [Azzy380/Attributes#9]
### What happened?

When you have this installed on the more up to date snapshot the snapshot wont load

### Generator version

Forge 1.19.2

### MCreator version

MCreator EAP 2023.1 b04717

### Relevant log output (optional)

```shell
2023-01-23-07:46:09 [main/INFO] [Launcher] Starting MCreator 2023.1.04717 EAP (04717) - 202300104717
2023-01-23-07:46:09 [main/INFO] [Launcher] Java version: 17.0.5, VM: OpenJDK 64-Bit Server VM, vendor: Eclipse Adoptium
2023-01-23-07:46:09 [main/INFO] [Launcher] Current JAVA_HOME for running instance:~~~~~2023.1 Snapshot\jdk
2023-01-23-07:46:09 [main/DEBUG] [Preferences Manager] Loading preferences from ~~~~~.mcreator\preferences
2023-01-23-07:46:09 [Thread-0/ERROR] [STDERR] Jan 23, 2023 7:46:09 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @12405818'
2023-01-23-07:46:10 [main/INFO] [Launcher] Installation path:~~~~~2023.1 Snapshot
2023-01-23-07:46:10 [main/INFO] [Launcher] User home of MCreator: ~~~~~.mcreator\
2023-01-23-07:46:10 [AWT-EventQueue-0/DEBUG] [Plugin Loader] Loading plugins from: .\plugins
2023-01-23-07:46:10 [AWT-EventQueue-0/DEBUG] [Plugin Loader] Loading plugins from: ~~~~~.mcreator\plugins
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: configuration_files from .\plugins\configuration_files.zip, weight: 3001
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Configuration Files] Config plugin was loaded
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: core from .\plugins\mcreator-core.zip, weight: 10
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: localization from .\plugins\mcreator-localization.zip, weight: 10
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: themes from .\plugins\mcreator-themes.zip, weight: 10
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: metadata_editor from .\plugins\metadata_editor.zip, weight: 10
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: curios_api_plugin from .\plugins\Nerdys_CuriosAPI_Plugin_2.zip, weight: 10
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [GeckoLib Plugin] Plugin was loaded
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: item_tooltips from .\plugins\ItemTooltips_0.zip, weight: 1
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: azz_tools from .\plugins\attributes-2-2-9_0.zip, weight: 0
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Attributes] Attributes plugin was loaded
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: generator-1.18.2 from .\plugins\generator-1.18.2.zip, weight: 0
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: generator-1.19.2 from .\plugins\generator-1.19.2.zip, weight: 0
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: generator-addon-1.19.x from .\plugins\generator-addon-1.19.x.zip, weight: 0
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: generator-datapack-1.18.x from .\plugins\generator-datapack-1.18.x.zip, weight: 0
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: generator-datapack-1.19.x from .\plugins\generator-datapack-1.19.x.zip, weight: 0
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: mcreator-link from .\plugins\mcreator-link.zip, weight: 0
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Plugin Loader] Loading plugin: reauth from .\plugins\reauth1.0.0.1.zip, weight: 0
2023-01-23-07:46:10 [AWT-EventQueue-0/DEBUG] [Theme Loader] Loading UI themes
2023-01-23-07:46:10 [AWT-EventQueue-0/INFO] [Theme Loader] Using MCreator UI theme: default_dark
2023-01-23-07:46:10 [Sound system/INFO] [STDOUT] Starting up SoundSystem...
2023-01-23-07:46:10 [Thread-3/INFO] [STDOUT] Initializing Java Sound
2023-01-23-07:46:10 [Thread-3/INFO] [STDOUT] (The Java Sound API.  For more information, see http://java.sun.com/products/java-media/sound/)
2023-01-23-07:46:11 [Thread-3/INFO] [STDOUT] JavaSound initialized.
2023-01-23-07:46:11 [AWT-EventQueue-0/INFO] [L10N] Setting default locale to: en_US
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added damagesources datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added potions datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added itemtypes datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added slot datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added defaultfeatures datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/WARN] [Data List Loader] Duplicate datalist key: FORGE:STEP_HEIGHT_ADDITION
2023-01-23-07:46:11 [AWT-EventQueue-0/WARN] [Data List Loader] Duplicate datalist key: FORGE:ATTACK_RANGE
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added attribute datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added blocksitems datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added tabs datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added projectiles datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added fluids datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added planttypes datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added gamemodes datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added entities datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added stepsounds datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added operation datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added biomes datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added soundcategories datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added mapcolors datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added pathnodetypes datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added achievements datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added enchantments datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added particles datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added enchantmenttypes datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added gamerules datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added keybuttons datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added sounds datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added mobspawntypes datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added screens datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added villagerprofessions datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added generationsteps datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added effects datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Data List Loader] Added materials datamap to cache
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Mod API manager] Loaded mod API definition: reauth
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Mod API manager] Loaded mod API definition: curios_api
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Mod API manager] Loaded mod API definition: mcreator_link
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Variable loader] Loading variable types
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Blockly JavaScript Files loader] Loading Blockly JavaScript files from plugins
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Blockly Toolboxes loader] Loading Blockly toolboxes from plugins
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Blockly loader] Loading blocks for procedures
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Blockly loader] Loading blocks for aitasks
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Blockly loader] Loading blocks for jsontriggers
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Blockly loader] Loading blocks for cmdargs
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Blockly loader] Loading blocks for features
2023-01-23-07:46:11 [AWT-EventQueue-0/DEBUG] [Entity Animations Loader] Loading entity animations
2023-01-23-07:46:11 [AWT-EventQueue-0/ERROR] [Exception] Uncaught exception in AWT-EventQueue-0
java.lang.NoClassDefFoundError: net/mcreator/element/RecipeType
	at net.azzier.attributes.Launcher.register(Launcher.java:44) ~[?:?]
	at net.mcreator.plugin.MCREvent.lambda$event$0(MCREvent.java:26) ~[mcreator.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.mcreator.plugin.MCREvent.lambda$event$1(MCREvent.java:26) ~[mcreator.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.mcreator.plugin.MCREvent.event(MCREvent.java:25) ~[mcreator.jar:?]
	at net.mcreator.ui.MCreatorApplication.<init>(MCreatorApplication.java:164) ~[mcreator.jar:?]
	at net.mcreator.ui.MCreatorApplication.lambda$createApplication$3(MCreatorApplication.java:253) ~[mcreator.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:741) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.mcreator.element.RecipeType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 21 more
```
```

**Comment by Azzy380** [comment]
New snapshot changed a bit in java plugins so it's not compatible at the moment

**Comment by NerdyPuzzle** [comment]
With the current version loading on 2023.1 (which I tested) this issue should now be closed.

**Comment by Azzy380** [comment]
c3264056618762bc3360cf40a15453826ff5ae27
